### ISSUE TITLE
Segmentation fault when executing jitted program

### ISSUE THREAD

**Issue by Officeyutong** [qmonnet/rbpf#88]
# Segmentation fault when executing the jitted ebpf program

## Description

Segmentation fault when executting the jitted ebpf program. But the same program works well when using intepreter mode.

## Cargo.toml
```toml
[package]
name = "rbpf-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rbpf = { git = "https://github.com/qmonnet/rbpf" }
```

## Rust program
```rust
fn main() {
    let prog = std::fs::read("prime.bpf.bin").unwrap();
    let mut vm = rbpf::EbpfVmRaw::new(Some(&prog)).unwrap();
    vm.jit_compile().unwrap();
    let mem = &mut [0x00];
    unsafe { vm.execute_program_jit(mem) }.unwrap();
}
```
## ebpf program
[prime.bpf.bin.zip](https://github.com/qmonnet/rbpf/files/12385628/prime.bpf.bin.zip)

It was zipped, since github does not support uploading `*.bin` files.

The ebpf program was compiled from the following C source using `clang 14.0.6`, then the `.text` segment was extracted using `llvm-objcopy`
```c
int main() {
  long cnt = 0;
  for (int i = 1; i < 1e4; i++) {
    int ok = 1;
    for (int j = 2; j * j <= i && ok; j++) {
      if (i % j == 0)
        ok = 0;
    }
    cnt += ok;
  }
  return cnt;
}
```
## How to trigger
```console
root@mnfe-pve:~/rbpf-poc# cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/rbpf-poc`
Segmentation fault
```
## Expected behavior
Program successfully exited with no exception

## Environment
```console
stable-x86_64-unknown-linux-gnu (default)
rustc 1.71.0 (8ede3aae2 2023-07-12)
```
```console
root@mnfe-pve:~/bpf-benchmark# uname -a
Linux mnfe-pve 6.2.16-6-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-7 (2023-08-01T11:23Z) x86_64 GNU/Linux
root@mnfe-pve:~/bpf-benchmark# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
root@mnfe-pve:~/bpf-benchmark# 
```
